# numpy教程-切片和索引

### 切片

切片是 Python 中基本切片概念到 n 维的扩展。 

通过将start，stop和step参数提供给内置的slice函数来构造一个slice对象。 

此slice对象被传递给数组来提取数组的一部分。

如果只输入一个参数，则将返回与索引对应的单个项目。 

如果使用`a:`，则从该索引向后的所有项目将被提取。 

如果使用两个参数（以:分隔），则对两个索引（不包括停止索引）之间的元素以默认步骤进行切片。

切片还可以包括省略号（...），返回指定维度(行, 列)的所有元素

如果在行位置使用省略号，它将返回包含行中元素的ndarray。

In [3]:
import numpy as np

a = np.arange(10)
# 创建slice对象
s = slice(2, 8, 2)

print(a)
print(s)
print(a[s])
print(a[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 8, 2)
[2 4 6]
[2 4 6]


In [5]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('取第二列元素')
print(a[..., 1])

print('取第二行元素')
print(a[1, ...])

print('取第二列及剩余元素')
print(a[..., 1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
取第二列元素
[2 4 5]
取第二行元素
[3 4 5]
取第二列及剩余元素
[[2 3]
 [4 5]
 [5 6]]


### 高级索引

高级索引**始终返回数据的副本**。 与此相反，切片只提供了一个视图。

有两种类型的高级索引：整数和布尔值。

### 整数索引

整数索引可以获取数组中的任意元素,索引就是通过指定array中的下标(行号和列号).

这里的array可以理解成线性代数的中的矩阵,索引就是矩阵中元素的下标.

In [8]:
import numpy as np

a = np.array([[1,  2],  [3,  4],  [5,  6]]) 
b = a[[0,1,2], [0, 1, 0]]

print(a)
print(b)
print('该结果包括数组中(0,0)，(1,1)和(2,0)位置处的元素。')

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
该结果包括数组中(0,0)，(1,1)和(2,0)位置处的元素。


In [17]:
import numpy as np

a = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])
print('创建一个 4×3 矩阵,[4行3列] ')
print(a)
print('取矩阵每个角落的元素')

rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])


b = a[rows, cols]
print(b)

创建一个 4×3 矩阵,[4行3列] 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
取矩阵每个角落的元素
[[ 0  2]
 [ 9 11]]


高级和基本索引可以通过使用切片:或省略号...与索引数组组合。 

以下示例使用slice作为列索引和高级索引。 

当切片用于两者时，结果是相同的。 

但高级索引会导致复制，并且可能有不同的内存布局。