# numpy教程-数组创建

### 使用empty, zeros和ones创建数组

numpy.empty: 创建指定大小和dtype的未初始化数组:

`numpy.empty(shape, dtype = float, order = 'C')`

numpy.zeros: 返回指定大小和dtype, 以 0 填充的新数组:

`numpy.zeros(shape, dtype = float, order = 'C')`

numpy.ones: 返回指定大小和dtype，以 1 填充的新数组:

`numpy.ones(shape, dtype = None, order = 'C')`

1.	Shape 空数组的形状，整数或整数元组
2.	Dtype 所需的输出数组类型，可选
3.	Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组

In [7]:
import numpy as np

a = np.empty([3,2], dtype=int)
print('使用empty创建数组, 注意：数组元素为随机值，因为它们未初始化。')
print(a)


print('使用zeros创建数组')
b = np.zeros([3, 3], dtype=int)
print(b)

print('使用ones创建数组')
c = np.ones([3, 3], dtype=int)
print(c)
print('创建含有 5 个 1 的数组，默认类型为 float  ')
d = np.ones(5)
print(d)


使用empty创建数组, 注意：数组元素为随机值，因为它们未初始化。
[[ 75236458     65923]
 [  5706353 192154228]
 [ 25363068  41746819]]
使用zeros创建数组
[[0 0 0]
 [0 0 0]
 [0 0 0]]
使用ones创建数组
[[1 1 1]
 [1 1 1]
 [1 1 1]]
创建含有 5 个 1 的数组，默认类型为 float  
[1. 1. 1. 1. 1.]


### 创建来自现有数据的array

`numpy.asarray`: 此函数类似于`numpy.array`，除了它有较少的参数, 对于将 Python 序列转换为ndarray非常有用。

`numpy.asarray(a, dtype = None, order = None)`

1.	a 任意形式的输入参数，比如列表、列表的元组、元组、元组的元组、元组的列表
2.	dtype 通常，输入数据的类型会应用到返回的ndarray
3.	order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组

In [12]:
import numpy as np

print('创建来自array的数组')
a = [1, 2, 3]
b = np.asarray(a)
c = np.asarray(a, dtype=float)
print(b)
print(c)

print('创建来自元组的数组')
a = (4, 5, 6)
b = np.asarray(a)
print(b)

print('创建来自元组列表的数组')
a = [(1,2,3), (5,6)]
b = np.asarray(a)
print(b)

创建来自array的数组
[1 2 3]
[1. 2. 3.]
创建来自元组的数组
[4 5 6]
创建来自元组列表的数组
[(1, 2, 3) (5, 6)]


### 创建来自缓冲区数据的array

`numpy.frombuffer`: 此函数将缓冲区解释为一维数组

`numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)`

1.	buffer 任何表示buffer的对象,即含有`__buffer__`方法的对象,例如:字符串就不是,但是bytes就是.
2.	dtype 返回数组的数据类型，默认为float
3.	count 需要读取的数据数量，默认为-1，读取所有数据
4.	offset 需要读取的起始位置，默认为0

In [15]:
import numpy as np

s = b'Hello World.'
a = np.frombuffer(s, dtype='S1')
print(a)

s = 'Hello World.'
a = np.frombuffer(s, dtype='S1')
print(a)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd' b'.']


AttributeError: 'str' object has no attribute '__buffer__'

### 创建来自可迭代对象的array

从可迭代对象构建一个ndarray对象，返回一个新的**一维数组**。

**注意:** dtype必须指定,没有默认值

`numpy.fromiter(iterable, dtype, count = -1)`

1.	iterable 任何可迭代对象
2.	dtype 返回数组的数据类型
3.	count 需要读取的数据数量，默认为-1，读取所有数据

In [19]:
import numpy as np

a = np.fromiter(range(5), dtype=int)
print(a)

b = np.fromiter([1, 2, 1, 2], dtype=float)
print(b)

c = np.fromiter(iter(range(5, 10)), dtype=complex)
print(c)

[0 1 2 3 4]
[1. 2. 1. 2.]
[5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


### 创建来自数值范围的array

`numpy.arange` : 返回包含给定范围内的等间隔值的array.

`numpy.arange(start, stop, step, dtype)`

1.	start 范围的起始值，默认为0
2.	stop 范围的终止值（不包含）
3.	step 两个值的间隔，默认为1
4.	dtype 返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

`numpy.linspace` : 指定了范围之间的均匀间隔数量，而不是步长.此函数类似于arange()函数。

`numpy.linspace(start, stop, num, endpoint, retstep, dtype)`

1.	start 序列的起始值
2.	stop 序列的终止值，如果endpoint为true，该值包含于序列中
3.	num 要生成的等间隔样例数量，默认为50
4.	endpoint 序列中是否包含stop值，默认为ture
5.	retstep 如果为true，返回样例，以及连续数字之间的步长
6.	dtype 输出ndarray的数据类型

`numpy.logspace` : 创建在对数刻度上均匀分布的数字的array, 刻度的开始和结束端点是某个底数的幂，通常为 10。

`numpy.logscale(start, stop, num, endpoint, base, dtype)`

1.	start 起始值是base ** start
2.	stop 终止值是base ** stop
3.	num 范围内的数值数量，默认为50
4.	endpoint 如果为true，终止值包含在输出数组当中
5.	base 对数空间的底数，默认为10
6.	dtype 输出数组的数据类型，如果没有提供，则取决于其它参数

In [6]:
import numpy as np

print('使用arange创建array')
a = np.arange(5)
print(a)

b = np.arange(5, 10, dtype=float)
print(b)

c = np.arange(2, 20, 2)
print(c)

print('使用linespace创建array')
a = np.linspace(10, 20, 5)
print(a)

b = np.linspace(1, 2, 5, retstep=True)
print(b)

使用arange创建array
[0 1 2 3 4]
[5. 6. 7. 8. 9.]
[ 2  4  6  8 10 12 14 16 18]
使用linespace创建array
[10.  12.5 15.  17.5 20. ]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
