# numpy教程-数组操作

NumPy包中有几个例程用于处理ndarray对象中的元素。 它们可以分为以下类型：

1.	reshape  不改变数据的条件下修改形状
    `numpy.reshape(arr, newshape, order')`
    * arr：要修改形状的数组
    * newshape：整数或者整数数组，新的形状应当兼容原有形状
    * order：'C'为 C 风格顺序，'F'为 F 风格顺序，'A'为保留原顺序。

2.	flat    数组上的一维迭代器

3.	flatten  返回折叠为一维的数组副本
    `ndarray.flatten(order)`
    * order：'C' – 按行，'F' – 按列，'A' – 原顺序，'k' – 元素在内存中的出现顺序。
    
4.	ravel   返回连续的展开数组,并且按需生成副本。返回的数组和输入数组拥有相同数据类型。
    `numpy.ravel(a, order)`
    * order：'C' – 按行，'F' – 按列，'A' – 原顺序，'k' – 元素在内存中的出现顺序。

In [4]:
import numpy as np

a = np.arange(8)

print(a)

print('改变数组形状:')
b = a.reshape(4, 2)
print(b)

a = np.arange(8).reshape(2, 4)
print('使用 flat 函数之后')
print(a.flat[5])

print('使用flatten展开数组:')
print(b.flatten())

print('以 F 风格顺序展开数组:')
print(a.flatten(order='F'))

print('使用ravel函数展开数组:')
print(b.ravel())

print('以 F 风格顺序调用ravel函数展开数组:')
print(a.ravel(order='F'))

[0 1 2 3 4 5 6 7]
改变数组形状:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
使用 flat 函数之后
5
使用flatten展开数组:
[0 1 2 3 4 5 6 7]
以 F 风格顺序展开数组:
[0 4 1 5 2 6 3 7]
使用ravel函数展开数组:
[0 1 2 3 4 5 6 7]
以 F 风格顺序调用ravel函数展开数组:
[0 4 1 5 2 6 3 7]


### 数组翻转操作

1.	transpose 翻转数组的维度,就是矩阵转置
    `numpy.transpose(arr, axes)`
    * arr：要转置的数组
    * axes：整数的列表，对应维度，通常所有维度都会翻转。
    
2.	ndarray.T 和self.transpose()相同

3.	rollaxis 该函数向后滚动特定的轴，直到一个特定位置
    `numpy.rollaxis(arr, axis, start)`
    * arr：输入数组
    * axis：要向后滚动的轴，其它轴的相对位置不会改变
    * start：默认为零，表示完整的滚动。会滚动到特定位置。
    
4.	swapaxes 互换数组的两个轴
    `numpy.swapaxes(arr, axis1, axis2)`
    * arr：要交换其轴的输入数组
    * axis1：对应第一个轴的整数
    * axis2：对应第二个轴的整数

In [15]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)

print('使用 transpose 转置:')
print(np.transpose(a))

print('使用 T 转置:')
print(a.T)

print('使用rollaxis函数:')
print(np.rollaxis(a, 1))

print('创建三维的 ndarray:')
a = np.arange(8).reshape(2,2,2)
print(a)
print('调用 rollaxis 函数：将轴 2 滚动到轴 0（宽度到深度）')
print(np.rollaxis(a, 2))

print('调用 rollaxis 函数：将轴 2 滚动到轴 1（宽度到深度）')
print(np.rollaxis(a, 2, 1))

print('调用swapaxes交换轴:')
print(np.swapaxes(a, 2, 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
使用 transpose 转置:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
使用 T 转置:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
使用rollaxis函数:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
创建三维的 ndarray:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
调用 rollaxis 函数：将轴 2 滚动到轴 0（宽度到深度）
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
调用 rollaxis 函数：将轴 2 滚动到轴 1（宽度到深度）
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
调用swapaxes交换轴:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


### 修改数组维度

1.	broadcast 产生模仿广播的对象
2.	broadcast_to 将数组广播到新形状
3.	expand_dims 扩展数组的形状
4.	squeeze 从数组的形状中删除单维条目