# numpy教程-切片和索引

### 切片

切片是 Python 中基本切片概念到 n 维的扩展。 

通过将start，stop和step参数提供给内置的slice函数来构造一个slice对象。 

此slice对象被传递给数组来提取数组的一部分。

如果只输入一个参数，则将返回与索引对应的单个项目。 

如果使用`a:`，则从该索引向后的所有项目将被提取。 

如果使用两个参数（以:分隔），则对两个索引（不包括停止索引）之间的元素以默认步骤进行切片。

切片还可以包括省略号（...），返回指定维度(行, 列)的所有元素

如果在行位置使用省略号，它将返回包含行中元素的ndarray。

In [3]:
import numpy as np

a = np.arange(10)
# 创建slice对象
s = slice(2, 8, 2)

print(a)
print(s)
print(a[s])
print(a[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 8, 2)
[2 4 6]
[2 4 6]


In [5]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('取第二列元素')
print(a[..., 1])

print('取第二行元素')
print(a[1, ...])

print('取第二列及剩余元素')
print(a[..., 1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
取第二列元素
[2 4 5]
取第二行元素
[3 4 5]
取第二列及剩余元素
[[2 3]
 [4 5]
 [5 6]]


### 高级索引

高级索引**始终返回数据的副本**。 与此相反，切片只提供了一个视图。

有两种类型的高级索引：整数和布尔值。

### 整数索引

整数索引可以获取数组中的任意元素,索引就是通过指定array中的下标(行号和列号).

这里的array可以理解成线性代数的中的矩阵,索引就是矩阵中元素的下标.

In [8]:
import numpy as np

a = np.array([[1,  2],  [3,  4],  [5,  6]]) 
b = a[[0,1,2], [0, 1, 0]]

print(a)
print(b)
print('该结果包括数组中(0,0)，(1,1)和(2,0)位置处的元素。')

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
该结果包括数组中(0,0)，(1,1)和(2,0)位置处的元素。


In [24]:
import numpy as np

a = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])
print('创建一个 4×3 矩阵,[4行3列] ')
print(a)
print('取矩阵每个角落的元素, 共 4 个元素, 每个元素都有行号列号, 因此共有4个行号,4个列号')

rows = np.array([[0,0], [3,3]])
print('行号有4个,依次: 0, 0, 3, 3')

cols = np.array([[0,2], [0,2]])
print('列号有4个,依次: 0, 2, 0, 2')

print('依次对应行列号: (0,0), (0,2), (3,0), (3,2)')
print('保留原格式展示:')
b = a[rows, cols]
print(b)

print('另外一种展示方式:')
rows = np.array([0,0,3,3])
cols = np.array([0,2,0,2])
c = a[rows, cols]
print(c)

创建一个 4×3 矩阵,[4行3列] 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
取矩阵每个角落的元素, 共 4 个元素, 每个元素都有行号列号, 因此共有4个行号,4个列号
行号有4个,依次: 0, 0, 3, 3
列号有4个,依次: 0, 2, 0, 2
依次对应行列号: (0,0), (0,2), (3,0), (3,2)
保留原格式展示:
[[ 0  2]
 [ 9 11]]
另外一种展示方式:
[ 0  2  9 11]


高级和基本索引可以通过使用切片:或省略号...与索引数组组合。 

以下示例使用slice作为列索引和高级索引。 

当切片用于两者时，结果是相同的。 

但高级索引会导致复制，并且可能有不同的内存布局。

In [29]:
import numpy as np 
a = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])
print('创建一个 4×3 矩阵,[4行3列] ')
print(a)

print('切片数组, 注意:切片是前闭后开的')
b = a[1:4, 1:3]
print(b)

print('混合使用切片和索引, 对列使用高级索引')
c = a[1:4, [1,2]]
print(c)

创建一个 4×3 矩阵,[4行3列] 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
切片数组, 注意:切片是前闭后开的
[[ 4  5]
 [ 7  8]
 [10 11]]
混合使用切片和索引, 对列使用高级索引
[[ 4  5]
 [ 7  8]
 [10 11]]


### 布尔索引

当结果对象是布尔运算（例如比较运算符）的结果时，将使用此类型的高级索引。

In [30]:
import numpy as np 
a = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])

print(a)
print('print大于5的元素')
b = a[a > 5]
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
print大于5的元素
[ 6  7  8  9 10 11]


In [33]:
import numpy as np 
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print(a)
print('使用 ~（取补运算符）过滤NaN元素:')
b = a[~np.isnan(a)]
print(b)

print('过滤非复数元素:')
a = np.array([1,  2+6j,  5,  3.5+5j])  
b = a[np.iscomplex(a)]
print(b) 

[nan  1.  2. nan  3.  4.  5.]
使用 ~（取补运算符）过滤NaN元素:
[1. 2. 3. 4. 5.]
过滤非复数元素:
[2. +6.j 3.5+5.j]


### 广播

广播是指 NumPy 在算术运算期间处理不同形状的数组的能力。

对数组的算术运算通常在相应的元素上进行。 

如果两个阵列具有完全相同的形状，则这些操作被无缝执行。

In [34]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
d = a + b
print(a)
print(b)
print(c)
print(d)

[1 2 3 4]
[10 20 30 40]
[ 10  40  90 160]
[11 22 33 44]


通常如果两个数组的维数不相同，则元素到元素的操作是不可能的。 

但是在 NumPy 中却可以对形状不相似的数组进行操作，因为它拥有广播功能。 

较小的数组会广播到较大数组的大小，以便使它们的形状可兼容。

如果满足以下规则，可以进行广播：

* ndim较小的数组会在前面追加一个长度为 1 的维度。

* 输出数组的每个维度的大小是输入数组该维度大小的最大值。

* 如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可计算它。

* 如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。


如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。

* 数组拥有相同形状。

* 数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。

* 数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。

In [36]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print('第一个数组:')
print(a)
print('第二个数组:')
print(b)
print('第一个数组 + 第二个数组:')
c = a + b
print(c)

第一个数组:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
第二个数组:
[1. 2. 3.]
第一个数组 + 第二个数组:
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


### 数组上的迭代

NumPy 有一个迭代器对象numpy.nditer。 它是一个多维迭代器对象，用于在数组上进行迭代。

数组的每个元素可使用 Python 的标准Iterator接口来访问。

In [ ]:
import numpy as np

a = np.arange(0, 60, 5)
a = a.reshape(3, 4)

print(a)

print('开始迭代数组:')
