# numpy教程-基本类型属性

### 安装

In [ ]:
pip install numpy

### Ndarray 对象

NumPy 中定义的最重要的对象是称为 ndarray 的 N 维数组类型。 它描述相同类型的元素集合。

ndarray中的每个元素在内存中使用相同大小的块。 ndarray中的每个元素是数据类型对象的对象（称为 dtype）。

### 创建ndarray

创建ndarray是使用 NumPy 中的数组函数创建的,即numpy.array

In [ ]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

1. object 任何暴露数组接口方法的对象都会返回一个数组或任何（嵌套）序列。
2. dtype 数组的所需数据类型，可选。
3. copy 可选，默认为true，对象是否被复制。
4. order C（按行）、F（按列）或A（任意，默认）。
5. subok 默认情况下，返回的数组被强制为基类数组。 如果为true，则返回子类。
6. ndimin 指定返回数组的最小维数。

### 创建ndarray示例

In [4]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([[1,2,3], [4, 5, 6]])

c = np.array([1,2,3,4], ndmin=2)

d = np.array([1,2,3], dtype=complex)

print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j]


### numpy中的数据类型

1.	bool_ 存储为一个字节的布尔值（真或假）
2.	int_ 默认整数，相当于 C 的long，通常为int32或int64
3.	intc 相当于 C 的int，通常为int32或int64
4.	intp 用于索引的整数，相当于 C 的size_t，通常为int32或int64
5.	int8 字节（-128 ~ 127）
6.	int16 16 位整数（-32768 ~ 32767）
7.	int32 32 位整数（-2147483648 ~ 2147483647）
8.	int64 64 位整数（-9223372036854775808 ~ 9223372036854775807）
9.	uint8 8 位无符号整数（0 ~ 255）
10.	uint16 16 位无符号整数（0 ~ 65535）
11.	uint32 32 位无符号整数（0 ~ 4294967295）
12.	uint64 64 位无符号整数（0 ~ 18446744073709551615）
13.	float_ float64的简写
14.	float16 半精度浮点：符号位，5 位指数，10 位尾数
15.	float32 单精度浮点：符号位，8 位指数，23 位尾数
16.	float64 双精度浮点：符号位，11 位指数，52 位尾数
17.	complex_ complex128的简写
18.	complex64 复数，由两个 32 位浮点表示（实部和虚部）
19.	complex128 复数，由两个 64 位浮点表示（实部和虚部）

### 数据类型对象 (dtype)

数据类型对象描述了对应于数组的固定内存块的解释，取决于以下方面：

* 数据类型（整数、浮点或者 Python 对象）

* 数据大小

* 字节序（小端或大端）

* 在结构化类型的情况下，字段的名称，每个字段的数据类型，和每个字段占用的内存块部分。

* 如果数据类型是子序列，它的形状和数据类型。

字节顺序取决于数据类型的前缀`<`或`>`。 

`<`意味着编码是小端（最小有效字节存储在最小地址中）。

`>`意味着编码是大端（最大有效字节存储在最小地址中）。

dtype可由一下语法构造:

In [ ]:
numpy.dtype(object, align, copy)

参数为：

* Object：被转换为数据类型的对象。

* Align：如果为true，则向字段添加间隔，使其类似 C 的结构体。

* Copy: 生成dtype对象的新副本，如果为flase，结果是内建数据类型对象的引用。

### dtype创建示例

In [10]:
import numpy as np

dt1 = np.dtype(np.int32)
print(dt1)
#int8，int16，int32，int64 可替换为等价的字符串 'i1'，'i2'，'i4'，以及其他。
dt2 = np.dtype('i4')
print(dt2)
# 使用端记号
dt3 = np.dtype('>i4')
print(dt3)
# 创建结构化数据类型
dt4 = np.dtype([('age', np.int8)])
print(dt4)
# 将数据类型应用到ndarray对象上
dt5 = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt5)
print(a)
# 文件名称可用于访问 age 列的内容  
print(a['age'])

int32
int32
>i4
[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]


In [15]:
import numpy as np

std = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(std)

a = np.array([('arvin', 21, 50), ('tom', 18, 75), ('jack', 26, 50)], dtype=std)
print(a)
print(a['name'])
print(a['age'])
print(a['marks'])

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'arvin', 21, 50.) (b'tom', 18, 75.) (b'jack', 26, 50.)]
[b'arvin' b'tom' b'jack']
[21 18 26]
[50. 75. 50.]


### 每个内建类型都有一个唯一定义它的字符代码


'b'：布尔值

'i'：符号整数

'u'：无符号整数

'f'：浮点

'c'：复数浮点

'm'：时间间隔

'M'：日期时间

'O'：Python 对象

'S', 'a'：字节串

'U'：Unicode

'V'：原始数据（void）

### ndarray属性

1. ndarray.shape : 返回一个数组维度的元组，也可以用于调整数组大小
2. ndarray.ndim : 返回数组的维数
3. ndarray.itemsize: 返回数组中每个元素的字节单位长度
4. ndarray.flags: 
    * C_CONTIGUOUS (C) 数组位于单一的、C 风格的连续区段内
    * F_CONTIGUOUS (F) 数组位于单一的、Fortran 风格的连续区段内
    * OWNDATA (O) 数组的内存从其它对象处借用
    * WRITEABLE (W) 数据区域可写入。 将它设置为flase会锁定数据，使其只读
    * ALIGNED (A) 数据和任何元素会为硬件适当对齐
    * UPDATEIFCOPY (U) 这个数组是另一数组的副本。当这个数组释放时，源数组会由这个数组中的元素更新

In [27]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])  
print(a.shape)

# 调整数组大小,调整为3行2列
a.shape = (3, 2)
print(a)

print('数组维度: {}'.format(a.ndim))

print('每个元素长度: {}字节'.format(a.itemsize))

print(a.flags)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
数组维度: 2
每个元素长度: 4字节
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [22]:
import numpy as np

a = np.arange(24)

print(a)
print(a.ndim)

b = a.reshape(2, 4, 3)

print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3
